Add: script check commit
What: add script too review commits
Why: start to build ci/cd

AG-34

diff --git a/.github/workflows/auto-merge.yml b/.github/workflows/auto-merge.yml
--- a/.github/workflows/auto-merge.yml
+++ b/.github/workflows/auto-merge.yml
@@ -1,13 +1,13 @@
 name: Auto Merge PR
 
 on:
-  pull_request:
-    types: [opened, synchronize, ready_for_review]
+  pull_request_review:
+    types: [submitted]
 
 jobs:
   auto-merge:
     runs-on: ubuntu-latest
-
+    if: github.event.review.state == 'approved'
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -27,6 +27,21 @@ jobs:
           else
             echo "PR is not approved. Exiting..."
             exit 1
+          fi
+
+      - name: Pass Pipeline
+        id: pass_pipeline
+        run: |
+          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/agenda-services/agenda/actions/runs?event=pull_request&status=failed")
+
+          FAILED_WORKFLOWS=$(echo "$WORKFLOW_RUNS" | jq '[.workflow_runs[] | select(.status=="failed")] | length')
+
+          if [ "$FAILED_WORKFLOWS" -gt 0 ]; then
+            echo "There are failed workflows. Exiting..."
+            exit 1
+          else
+            echo "All workflows passed."
           fi
 
       - name: Auto merge PR
